### ISSUE TITLE
ANSWER: algorithm contrast ratio

### ISSUE THREAD

**Issue by joanebrown** [siege-media/contrast-ratio#24]
Hi!

I love your algorithm :P Could you tell me what's the formula? I want to use this in my application, but on server side (php). I tried a lot of algorithms, but any  doesn't work so well as yours.

I want to know what font color I have to use (black or white) if I know the background color.

I hope not to bother you with my question.

BTW: I tried to read your code, But I get lost in so many lines of code hehe

Regards!!

**Comment by LeaVerou** [comment]
That's the whole point of open source: I don't need to "tell" you any formula, because **the entire code is right here, in the repo**.
There are only TWO non-minified js files in this repo, of less than 500 lines TOTAL. Did you bother to look through them at all? It would have taken one minute.
In any case, this is the relevant bit: https://github.com/LeaVerou/contrast-ratio/blob/gh-pages/color.js#L108
